# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: 12.8
      - name: npm dependencies
        run: npm install     
      - name: Build
        run: npm run build -- --prod
        
      - name: Git deploy to Heroku
        # You may pin to the exact commit or the version.
        # uses: onekiloparsec/heroku-node-deploy-subfolder@2e8f857249dd4915d62689c96ce32e16b7be5a44
        uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
        with:
          # Your Heroku API key. This will be used for authentication. You can find it in your Heroku account settings
          api_key: ffa9ea1b-c6ec-4dde-b434-f75e12238161
          # The email of your Heroku account.
          email: jcmail.am@gmail.com
          # The app name to use for deploying/updating
          app_name: sg-beauty-client-app
          # The branch that you would like to deploy to Heroku
          branch: master
          # The subfolder where your built code is sitted, e.g. `dist`.
          subfolder: dist
